---
title: "Map Code"
author: "Team 6: Trendsetters"
date: "3/12/2020"
output: html_document
---

## Map Code ##

```{r message=FALSE}
library(dplyr)
library(ggplot2)
library(ggmap)
library(maptools)
library(maps)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(data.table)
library(ggsn) # for scale bar `scalebar`
library(ggrepel) # if need to repel labels 
```

```{r}
covid <- read.csv("./Datasets/covid_19_data.csv", stringsAsFactors = FALSE)
covid <- covid %>% filter(ObservationDate == "03/02/2020")

## World Final Map ##

world <- ne_countries(scale = "medium", returnclass = "sf")
total <- covid %>% group_by(Country.Region) %>% summarise(total=sum(Confirmed))

fix <- (unique(total$Country.Region) %in% world$admin) # check which names to fix
for(i in 1:length(fix)){
  if(fix[i]==FALSE){
    print(total$Country.Region[i])
  }
}

total$Country.Region <- recode(total$Country.Region, `Mainland China`="China",
                               US="United States of America",
                               `Hong Kong`="Hong Kong S.A.R.",
                               Macau="Macao S.A.R",
                               `North Macdeonia`="Macedonia",
                               UK="United Kingdom")

world2 <- merge(world, total, by.x="admin", by.y="Country.Region", all.x=TRUE)
world2[is.na(world2$total),"total"] <- 0
world2$range <- cut(world2$total, breaks=c(-Inf,10,20,30,40,50,100,200,5000,Inf), right=TRUE)

ggplot(data = world2) +
  geom_sf(aes(fill = range)) +
  scale_fill_brewer(palette="YlOrRd",
                    name="Count of Confirmed Coronavirus Cases",
                    labels=c("<10","10-20","21-30","31-40","41-50","51-100","101-200","201-5000","5000+")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))
```

```{r}
## China Final Map ##
china_map <- rgdal::readOGR("bou2_4p.shp")
china_province = setDT(china_map@data)
setnames(china_province, "NAME", "province")

# transform to UTF-8 coding format
china_province[, province:=iconv(province, from = "GBK", to = "UTF-8")] 
# create id to join province back to lat and long, id = 0 ~ 924
china_province[, id:= .I-1] 
china_province[, province:= as.factor(province)]

dt_china = setDT(fortify(china_map))
dt_china[, id:= as.numeric(id)]

setkey(china_province, id); setkey(dt_china, id)
dt_china <- china_province[dt_china]

# make the province EN, CH label file
province_CH <- china_province[, levels(china_province$province)]
province_EN <- c("Shanghai", "Yunnan", "Inner Mongolia", "Beijing", "Taiwan",
                 "Jilin", "Sichuan", "Tianjin", "Ningxia", "Anhui",
                 "Shandong", "Shanxi", "Guangdong", "Guangxi", "Xinjiang",
                 "Jiangsu", "Jiangxi", "Hebei", "Henan", "Zhejiang",
                 "Hainan", "Hubei", "Hunan", "Gansu", "Fujian",
                 "Tibet", "Guizhou", "Liaoning", "Chongqing", "Shaanxi",
                 "Qinghai", "Hong Kong", "Heilongjiang"
)

value <- c()
for(i in 1:length(province_EN)){
  value <- c(value, covid[covid$Province.State==province_EN[i],"Confirmed"])
}

input_data <- data.table(province_CH, province_EN, value)
setkey(input_data, province_CH)
setkey(dt_china, province)
china_map_pop <- input_data[dt_china[AREA>0.1,]]

label_dt <- china_map_pop[, .(x = mean(range(long)), y = mean(range(lat)), province_EN, province_CH), by = id]
label_dt <- unique(label_dt)
setkey(label_dt, province_EN)
# I have fine-tuned the label position of some provinces
label_dt['Inner Mongolia', `:=` (x = 110, y = 42)]
label_dt['Gansu', `:=` (x = 96.3, y = 40)]
label_dt['Hebei', `:=` (x = 115.5, y = 38.5)]
label_dt['Liaoning', `:=` (x = 123, y = 41.5)]

label_dt <- label_dt[-1]
china_map_pop <- china_map_pop %>% filter(!is.na(value))
china_map_pop$range <- cut(china_map_pop$value, breaks=c(0,100,500,1000,1500,Inf))

ggplot(china_map_pop, aes(x = long, y = lat, group = group, fill=range)) +
  labs(fill = "Count of Confirmed Coronavirus Cases")+
  geom_polygon()+
  geom_path()+
  scale_fill_brewer(palette="YlOrRd", labels=c("0-100","101-500","501-1000","1001-1500","1500+"))+
  blank() +
  geom_text(data = label_dt, aes(x=x, y=y, label = province_EN),inherit.aes = F) +
  scalebar(data = china_map_pop, dist = 500, dist_unit = "km",
         transform = T, model = "WGS84",
         border.size = 0.4, st.size = 2)
```